spring.application.name=GestionStockApp
security.jwt.secret-key=qG9A1tZ5Lw0fD3fEmW1gQQ6BslBzKcPZ9T6F3eF+YI4=
security.jwt.expiration-time=3600000

# Configuration Swagger-UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# Configuration du serveur email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=issadiol99@gmail.com
spring.mail.password=778170068Diol
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Autres paramètres de l'application
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Configuration pour l'exécution asynchrone des emails
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10
spring.task.execution.pool.queue-capacity=25