spring.application.name=GestionStockApp
security.jwt.secret-key=qG9A1tZ5Lw0fD3fEmW1gQQ6BslBzKcPZ9T6F3eF+YI4=
security.jwt.expiration-time=3600000

# Configuration Swagger-UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha