spring:
  datasource:
    url: jdbc:postgresql://ep-round-salad-a5pr21up.us-east-2.aws.neon.tech/GestionStock?user=GestionStock_owner&password=DAz8PxIONCe3&sslmode=require
    password: DAz8PxIONCe3
    username: GestionStock_owner
    driver-class-name: org.postgresql.Driver
  jpa :
    hibernate:
      ddl-auto: update
server:
  port: 8081
