spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestiona_app
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa :
    hibernate:
      ddl-auto: update
server:
  port: 8081
cloudinary:
  cloud_name: dj31m8jdj
  api_key: 644751775479442
  api_secret: Y7xiIDvr3xR_NR54vBhAhXJR3lI
app:
  base-url: http://localhost:8081